### ISSUE TITLE
Help me tipbot

### ISSUE THREAD

**Issue by royalwebgrup** [MSFTserver/TipBot#1]
You mean ?
wallet folder found in %appdata% (default Roaming Folder):

**Comment by MSFTserver** [comment]
yes

**Comment by royalwebgrup** [comment]
so the script is put in the coin folder?

**Comment by MSFTserver** [comment]
just the config options for the wallet
```
server=1 par=1 rpcbind=127.0.0.1 rpcallowip=127.0.0.1 rpcport=3335 rpcuser=<Same-as-you-set-in-config.json> rpcpassword=<Same-as-you-set-in-config.json> rpcclienttimeout=30 rpcthreads=<Number-of-Threads> rpcworkqueue=1000
```
the other config is in config/default.json wich is for the bot to connect to the wallet with the config options we set for the wallet

**Comment by royalwebgrup** [comment]
ok thanks the information but there is 1 more thing that make me confused
when i make a bot, the bot is off in discord
how to activate it ??

**Comment by MSFTserver** [comment]
you have to add it to your server if you haven't done that and when you run node ./bot/bot.js the bit should pop online

I use this to create links and add my bots to servers 
https://discordapi.com/permissions.html

**Comment by royalwebgrup** [comment]
do you choose anything?
I think it's too much

**Comment by MSFTserver** [comment]
i just give it the ability to send messages and links ect. doesnt need anything else really, after you make the link click it and itll redirect you to what servers you can put the bot in, select the server you want the bot to be in and run the command stated earlier

**Comment by MSFTserver** [comment]
feel free to re-open this if you still have issue
