### ISSUE TITLE
custom function example?

### ISSUE THREAD

**Issue by GregoryGHarding** [MSFTserver/TipBot#12]
theres no documentation on how to implement a custom function, ive got commands down pat, is it possible to get an example script?

**Comment by MSFTserver** [comment]
https://github.com/MSFTserver/TipBot/blob/master/bot/modules/exampleTipper.js

**Comment by MSFTserver** [comment]
for non tipping commands i usually run another bot so the code doesnt get all messed up or somwthing goes wrong cause tipbot holds actuall value in it, if you want another bot that runs normal commands and such i have one here https://github.com/MSFTserver/RVN-Veronica

**Comment by GregoryGHarding** [comment]
i just want an example template to implement a custom function, not a command.

**Comment by MSFTserver** [comment]
https://github.com/MSFTserver/RVN-Veronica/blob/master/bot/modules/example.js

**Comment by GregoryGHarding** [comment]
thanks
