### ISSUE TITLE
multiple reply from bot

### ISSUE THREAD

**Issue by AstaClover** [MSFTserver/TipBot#17]
![screenshot 94](https://user-images.githubusercontent.com/45400747/50575755-1b952b00-0e3f-11e9-8e5c-fc0ae02cb43d.png)

how to fix this sir???

**Comment by MSFTserver** [comment]
you must be running 4 instances of the bot

**Comment by MSFTserver** [comment]
id check your process manager and see if there are multiple instances running.

**Comment by AstaClover** [comment]
![screenshot 98](https://user-images.githubusercontent.com/45400747/50583870-ca208680-0ea6-11e9-87e6-9ad3cf10a610.png)

**Comment by AstaClover** [comment]
should i use other vps?

**Comment by MSFTserver** [comment]
check the task manager not the pm2 internal one, one time this happened to me with pm2 crashing and restarting to fast for some reason it launched multiple one time

**Comment by AstaClover** [comment]
should I check on pm2 website manager?

**Comment by AstaClover** [comment]
ok thanks ! prolem is fixed

**Comment by MSFTserver** [comment]
awesome 👍
