### ISSUE TITLE
setup wallet from different pc

### ISSUE THREAD

**Issue by SACdeTERRE** [MSFTserver/TipBot#24]
I was wondering how can i setup a wallet that is located in another pc

**Comment by MSFTserver** [comment]
see issue #16

**Comment by SACdeTERRE** [comment]
I add ‘Host’ with the ip of my other pc and doesnt work

Envoyé de mon iPhone

Le 19 févr. 2019 à 20:31, MSFTserver <notifications@github.com<mailto:notifications@github.com>> a écrit :


see issue #16<https://github.com/MSFTserver/TipBot/issues/16>

**Comment by MSFTserver** [comment]
Closing this issue for now, can reopen if this is still an issue
