### ISSUE TITLE
Cannot read property "send" of undefined | bot.js:100:5

### ISSUE THREAD

**Issue by trial123Zel** [MSFTserver/TipBot#6]
I am receiving the below error. All other steps have worked, have created the coinTipper file, modified the coinD.conf and tipbot config files, bot connects to discord, pm2 launches the bot successfully. It just continually restarts with this one error in the log.

`July 25th 2018, 12:30:57 pm: [07-25-2018 12:30 pm PST][TipBot] uncaughtException: TypeError: Cannot read property 'send' of undefined
5|TipBot  | July 25th 2018, 12:30:57 pm: C:\Users\User\Downloads\Discord-TipBot-master\Discord-TipBot-master\bot\bot.js:100
5|TipBot  |     .send('[' + time + ' PST][' + pm2Name + '] uncaughtException: ' + err);
5|TipBot  |     ^
5|TipBot  |
5|TipBot  | TypeError: Cannot read property 'send' of undefined
5|TipBot  |     at process.on.err (C:\Users\User\Downloads\Discord-TipBot-master\Discord-TipBot-master\bot\bot.js:100:5)
5|TipBot  |     at emitOne (events.js:121:20)
5|TipBot  |     at process.emit (events.js:211:7)
5|TipBot  |     at process._fatalException (bootstrap_node.js:378:26)
5|TipBot  | July 25th 2018, 12:30:57 pm: WARNING: NODE_APP_INSTANCE value of '0' did not match any instance config file names.
5|TipBot  | July 25th 2018, 12:30:57 pm: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
5|TipBot  | July 25th 2018, 12:30:57 pm: [07-25-2018 12:30 pm PST][TipBot] 3 aliases Loaded!
5|TipBot  | July 25th 2018, 12:30:57 pm: (node:5124) Warning: N-API is an experimental feature and could change at any time.`

**Comment by MSFTserver** [comment]
so either bot token is wrong or the channel id for a log channel is wrong
